name: FEniCS_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          which python

      - name: Mamba install FEniCS
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          mamba create -n fenicsproject -c conda-forge fenics 
          conda activate fenicsproject
          which python
          python -c "from dolfin import *"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Install fenics-pymc3
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install -e .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pytest tests -vvv


